(source melpa)
(source marmalade)

(depends-on "popwin")
(depends-on "helm")
(depends-on "helm-ag")
(depends-on "helm-gtags")
(depends-on "auto-async-byte-compile")
(depends-on "highlight-parentheses")
(depends-on "inkpot-theme")
(depends-on "markdown-mode")
(depends-on "android-mode")
(depends-on "migemo")
(depends-on "paredit")
