(source melpa)
(source marmalade)

(depends-on "use-package")
(depends-on "popwin")
(depends-on "helm")
(depends-on "helm-gtags")
(depends-on "auto-async-byte-compile")
(depends-on "highlight-parentheses")
(depends-on "inkpot-theme")
(depends-on "markdown-mode")
(depends-on "mkdown")
(depends-on "lua-mode")
(depends-on "web-mode")
(depends-on "php-mode")
(depends-on "ws-butler")
