(source melpa)
(source marmalade)
(source gnu)

(depends-on "use-package")
(depends-on "popwin")
(depends-on "helm")
(depends-on "helm-gtags")
(depends-on "helm-ag")
(depends-on "auto-async-byte-compile")
(depends-on "highlight-parentheses")
(depends-on "inkpot-theme")
(depends-on "markdown-mode")
(depends-on "web-mode")
(depends-on "php-mode")
(depends-on "ws-butler")
(depends-on "js2-mode")
(depends-on "json-mode")
(depends-on "flycheck")
(depends-on "flycheck-pyflakes")
; (depends-on "cider")
(depends-on "yaml-mode")
(depends-on "dockerfile-mode")
(depends-on "editorconfig")
(depends-on "meghanada")
(depends-on "adoc-mode")
